syntax = "proto3";

package meshtastic;

import "nanopb.proto";

option csharp_namespace = "Meshtastic.Protobufs";
option go_package = "github.com/meshtastic/go/generated";
option java_outer_classname = "X3dhPayloadProtos";
option java_package = "org.meshtastic.proto";
option swift_prefix = "";
option (nanopb_fileopt).include = "<vector>";

message OneTimePreKey {
    
    /*
     * Random, unique key-ID allowing matching of private and public key
     */
    uint32 id = 1;

    /*
     * Id of node this key was sent to
     */
    optional uint32 node_num = 2;

    /*
     * 32-byte Ecliptic (X25519) key
     * Public for device-to-device communication, private for on-device-storage
     */
    bytes key = 3;
}

message PreKeyBundle {

    /*
     * NodeNum of pre-key-bundle for further correct handeling
     */
    optional uint32 node_num = 1;

    /*
     * 32-byte XEdDSA key, used for creating the pre-key signature
     */
    bytes identity_key = 2;

    /*
     * 32-byte Ecliptic (X25519) key, rotated occasionally
     */
    bytes signed_pre_key = 3;

    /*
     * 64 byte signature of the pre-key, signed by the identity key
     */
    bytes pre_key_signature = 4;

    /*
     * One or multiple Ecliptic (X25519) keys, only used once
     */
    repeated OneTimePreKey one_time_pre_keys = 5;
}

message OneTimePreKeyBundle {

    /*
     * Multiple one-time pre-keys, amount only limited by the available size per mesh packet
     */
    repeated OneTimePreKey one_time_pre_keys = 2;
}

message RequestBundle {

    /*
     * Number of the external node holding the key bundle
     */
    uint32 node_num = 1;

    /*
     * Matching public key to the node number
     */
    bytes public_key = 2;
}

/*
 * This payload contains no field for the public identity key of the sender, since it is saved as the public key in the mesh packet header
 */
message InitialMessage {
    
    /*
     * Public, ephermal key used by the sending node for this X3DH
     */
    bytes ephermal_key = 1;

    /*
     * Unique id of the used one-time pre key, so the receiving node can use the correct matching private one
     */
    uint32 otpk_id = 2;

    /*
     * Initial cyphertext containing e.g. further secrets for future protocol usage
     */
    bytes initial_cyphertext = 3;
}

